// <auto-generated />
using System;
using BitcoinIndexer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BitcoinIndexer.Infrastructure.Migrations
{
    [DbContext(typeof(BitcoinIndexerDbContext))]
    partial class BitcoinIndexerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BitcoinIndexer.Core.Models.AddressMetadata", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("boolean")
                        .HasColumnName("is_watched");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<long>("TotalReceivedSats")
                        .HasColumnType("bigint")
                        .HasColumnName("total_received_sats");

                    b.Property<long>("TotalSentSats")
                        .HasColumnType("bigint")
                        .HasColumnName("total_sent_sats");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Address");

                    b.HasIndex("IsWatched");

                    b.HasIndex("LastSeenAt");

                    b.ToTable("address_metadata", (string)null);
                });

            modelBuilder.Entity("BitcoinIndexer.Core.Models.BlockInfo", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DifficultyTarget")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("difficulty_target");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("MerkleRoot")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("merkle_root");

                    b.Property<long>("Nonce")
                        .HasColumnType("bigint")
                        .HasColumnName("nonce");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("previous_hash");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Hash");

                    b.HasIndex("Height");

                    b.HasIndex("Timestamp");

                    b.ToTable("block_info", (string)null);
                });

            modelBuilder.Entity("BitcoinIndexer.Core.Models.IndexProgress", b =>
                {
                    b.Property<bool>("Id")
                        .HasColumnType("boolean")
                        .HasColumnName("id");

                    b.Property<string>("LastBlockHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_block_hash");

                    b.Property<int>("LastHeight")
                        .HasColumnType("integer")
                        .HasColumnName("last_height");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("index_progress", (string)null);
                });

            modelBuilder.Entity("BitcoinIndexer.Core.Models.Transaction", b =>
                {
                    b.Property<string>("Txid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("txid");

                    b.Property<string>("BlockHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("block_hash");

                    b.Property<int?>("BlockHeight")
                        .HasColumnType("integer")
                        .HasColumnName("block_height");

                    b.Property<DateTime?>("BlockTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("block_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("FeeSats")
                        .HasColumnType("bigint")
                        .HasColumnName("fee_sats");

                    b.Property<bool>("IsCoinbase")
                        .HasColumnType("boolean")
                        .HasColumnName("is_coinbase");

                    b.Property<int?>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Txid");

                    b.HasIndex("BlockHash");

                    b.HasIndex("BlockHeight");

                    b.HasIndex("BlockTime");

                    b.HasIndex("IsCoinbase");

                    b.ToTable("transaction", (string)null);
                });

            modelBuilder.Entity("BitcoinIndexer.Core.Models.TransactionInput", b =>
                {
                    b.Property<string>("Txid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("txid");

                    b.Property<int>("Vout")
                        .HasColumnType("integer")
                        .HasColumnName("vout");

                    b.Property<string>("PrevTxid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prev_txid");

                    b.Property<int>("PrevVout")
                        .HasColumnType("integer")
                        .HasColumnName("prev_vout");

                    b.Property<string>("ScriptSig")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("script_sig");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<string>("TransactionTxid")
                        .HasColumnType("character varying(64)")
                        .HasColumnName("transaction_txid");

                    b.Property<string>("Witness")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("witness");

                    b.HasKey("Txid", "Vout");

                    b.HasIndex("TransactionTxid");

                    b.HasIndex("Txid");

                    b.HasIndex("PrevTxid", "PrevVout");

                    b.ToTable("transaction_input", (string)null);
                });

            modelBuilder.Entity("BitcoinIndexer.Core.Models.TransactionOutput", b =>
                {
                    b.Property<string>("Txid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("txid");

                    b.Property<int>("Vout")
                        .HasColumnType("integer")
                        .HasColumnName("vout");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address");

                    b.Property<string>("ScriptAsm")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("script_asm");

                    b.Property<string>("ScriptHex")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("script_hex");

                    b.Property<string>("ScriptType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("script_type");

                    b.Property<string>("TransactionTxid")
                        .HasColumnType("character varying(64)")
                        .HasColumnName("transaction_txid");

                    b.Property<long>("ValueSats")
                        .HasColumnType("bigint")
                        .HasColumnName("value_sats");

                    b.HasKey("Txid", "Vout");

                    b.HasIndex("Address");

                    b.HasIndex("TransactionTxid");

                    b.HasIndex("Txid");

                    b.ToTable("transaction_output", (string)null);
                });

            modelBuilder.Entity("BitcoinIndexer.Core.Models.TransactionReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address");

                    b.Property<int?>("BlockHeight")
                        .HasColumnType("integer")
                        .HasColumnName("block_height");

                    b.Property<int?>("BlockTimestamp")
                        .HasColumnType("integer")
                        .HasColumnName("block_timestamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<string>("ReceiverAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receiver_address");

                    b.Property<string>("SenderAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sender_address");

                    b.Property<string>("Txid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("txid");

                    b.Property<long>("ValueSats")
                        .HasColumnType("bigint")
                        .HasColumnName("value_sats");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.HasIndex("BlockHeight");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Txid");

                    b.HasIndex("Txid", "Address", "Direction")
                        .IsUnique();

                    b.ToTable("tx_reference", (string)null);
                });

            modelBuilder.Entity("BitcoinIndexer.Core.Models.Utxo", b =>
                {
                    b.Property<string>("Txid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("txid");

                    b.Property<int>("Vout")
                        .HasColumnType("integer")
                        .HasColumnName("vout");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address");

                    b.Property<string>("BlockHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("block_hash");

                    b.Property<int?>("BlockHeight")
                        .HasColumnType("integer")
                        .HasColumnName("block_height");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("ScriptHex")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("script_hex");

                    b.Property<DateTime?>("SpentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("spent_at");

                    b.Property<string>("SpentByTxid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("spent_by_txid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("ValueSats")
                        .HasColumnType("bigint")
                        .HasColumnName("value_sats");

                    b.HasKey("Txid", "Vout");

                    b.HasIndex("Address");

                    b.HasIndex("BlockHash");

                    b.HasIndex("BlockHeight");

                    b.HasIndex("Address", "Status", "BlockHeight");

                    b.ToTable("utxo", (string)null);
                });

            modelBuilder.Entity("BitcoinIndexer.Core.Models.WatchTarget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Account")
                        .HasColumnType("integer")
                        .HasColumnName("account");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DerivationScheme")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("derivation_scheme");

                    b.Property<int>("GapLimit")
                        .HasColumnType("integer")
                        .HasColumnName("gap_limit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Xpub")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("xpub");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique()
                        .HasFilter("\"address\" IS NOT NULL");

                    b.ToTable("watch_target", (string)null);
                });

            modelBuilder.Entity("BitcoinIndexer.Core.Models.WatchedScript", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address");

                    b.Property<string>("ScriptHex")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("script_hex");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.HasIndex("ScriptHex")
                        .IsUnique();

                    b.HasIndex("TargetId");

                    b.HasIndex("Type");

                    b.ToTable("watched_script", (string)null);
                });

            modelBuilder.Entity("BitcoinIndexer.Core.Models.TransactionInput", b =>
                {
                    b.HasOne("BitcoinIndexer.Core.Models.Transaction", null)
                        .WithMany("Inputs")
                        .HasForeignKey("TransactionTxid");
                });

            modelBuilder.Entity("BitcoinIndexer.Core.Models.TransactionOutput", b =>
                {
                    b.HasOne("BitcoinIndexer.Core.Models.Transaction", null)
                        .WithMany("Outputs")
                        .HasForeignKey("TransactionTxid");
                });

            modelBuilder.Entity("BitcoinIndexer.Core.Models.WatchedScript", b =>
                {
                    b.HasOne("BitcoinIndexer.Core.Models.WatchTarget", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("BitcoinIndexer.Core.Models.Transaction", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("Outputs");
                });
#pragma warning restore 612, 618
        }
    }
}
